server:
  compression:
    enabled: true
  servlet:
    context-path: /
  error:
    include-stacktrace: never
  http2:
    enabled: true
spring:
  # 数据源
  datasource:
    # 始终初始化数据
    continue-on-error: true
    initialization-mode: always
#    schema: classpath:/data/schema-mysql.sql
#    data: classpath:/data/data-mysql.sql

    url: jdbc:log4jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password:


#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver

    logSlowSql: true
    platform: h2



  jpa:
    show-sql: false
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none
#  # Redis
##  redis:
##    host: 127.0.0.1
##    password:
##    # 数据库索引 默认0
##    database: 0
##    port: 6379
##    timeout: 3000
#  # Elasticsearch
#
## Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/dao/*Dao.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: .**.entity
#  typeEnumsPackage: com.minlia.app.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    is-refresh: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false





#application:
#  # 全局限流
#  rateLimit:
#    enable: true
#    # 每1秒内
#    timeout: 3
#    # 总限制100个请求
#    limit: 100
#  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
#  auditRecord:
#    es: false
#  # 日志记录方式 true使用Elasticsearch记录 false记录至数据库中
#  accessRecord:
#    es: false




system:
# Swagger界面内容配置
  swagger:
    title: QQ接口文档
    description: QQ Api Documentation
    version: 1.0.0
    termsOfServiceUrl: https://www.qq.com
    contact:
      name: will
      url: https://www.qq.com
      email: 111111@qq.com

  problem:
    code-portal-prefix: http://code.qq.com/
  ignored:
    urls:
      - /api/v1/permission/getMenuList/**
      - /api/v1/user/regist
      - /api/v1/common/**
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /api/v1/open/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
security:
  basic:
    enabled: false

logging:
  level:
    ROOT: info
    com.minlia: debug
    hk.com.jetco.ekyc: trace
    jdbc.audit: error
    jdbc.sqltiming: error
    jdbc.resultset: error
    jdbc.connection: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    org.springframework.boot.autoconfigure: info
    org.springframework.boot.web.servlet.context: debug
