server:
  compression:
    enabled: true
  servlet:
    context-path: /
  error:
    include-stacktrace: never
  http2:
    enabled: true
spring:
  application:
    name: @project.name@
  profile: dev-h2
  datasource:
    continue-on-error: true
    initialization-mode: always
#    schema: classpath:/data/schema-mysql.sql
#    data: classpath:/data/data-mysql.sql
    url: jdbc:log4jdbc:h2:mem:TEST;MVCC=true;DB_CLOSE_DELAY=-1;MODE=Oracle
    driver-class-name: net.sf.log4jdbc.DriverSpy
    username: root
    password:

#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver

    logSlowSql: true
    platform: h2


  jpa:
    show-sql: false
    # 自动生成表结构
    generate-ddl: true
    hibernate:
      ddl-auto: none


## Mybatis-plus
mybatis-plus:
  # 放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/dao/*Dao.xml
  #实体扫描，多个package用逗号或者分号分隔
#  typeAliasesPackage: .**.entity
#  typeEnumsPackage: com.minlia.app.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 2
    #字段策略 0:"忽略判断",1:"非 NULL 判断",2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    is-refresh: true
    #数据库大写下划线转换
    #capital-mode: true
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false




## 基础系统配置
system:
  ### 安全相关配置
  security:
    #### 是否启用安全功能
    enabled: true
    ### 发行人
    issuer: minlia.com
    #### 当前系统的JWT密钥，用于生成Access Token
    secret-key: bWlubGlhOEVWNkh5NVwNRks0RUVBQ0lEQXdRdXMK
    #### 有效时限秒
    token-validity-in-seconds: 1800
    #### 记住当前登录用户的有效时限秒
    token-validity-in-seconds-for-remember-me: 2592000
    #### 接收Access Token的Header参数名称
    authentication-header-name: X-Auth-Token

  ### 接口文档SWAGGER相关配置
  swagger:
    #### 是否启用接口文档功能，一般生产环境需要将此关闭
    enabled: true
    ### 使用MAVNE里定义的变量，@MAVEN_VARIABLE_STRING@打包时会将此内容替换为真正的内容
    description: @project.description@
    title: @project.name@
    version: @project.version@
    termsOfServiceUrl: @project.url@
    contact:
      name: will
      url: @project.url@
      email: @project.url@
    ### key-name 优先使用变量的方式， 如找不到则使用冒号后面的默认值，也可以直接写为指定的值，如：X-Auth-Token
    key-name: ${system.security.authentication-header-name:X-Auth-Token}
  ### 跨域请求配置
  cors:
    ### 允许访问的域名
    allowed-origins: "*"
    ### 允许的方法集
    allowed-methods: GET, PUT, POST, DELETE, OPTIONS, PATCH
    ### 允许的头部
    allowed-headers: "*"
    ### exposed-headers 优先使用变量的方式， 如找不到则使用冒号后面的默认值，也可以直接写为指定的值，如：X-Auth-Token
    exposed-headers: ${system.security.authentication-header-name:X-Auth-Token}
    ### 充许传递Cookies
    allow-credentials: true
    max-age: 3600

  ### 国际化相关配置
  i18n:
    ### 语言切换头部参数名 值为语言加国家的形式。如：zh_CN en_US
    language-request-header-parameter-name: X-Request-Lang
    ### 使用可合并的国际化译文，不同类路径下的同名文件将被合并
    basename: i18n/messages


  ### 错误码展示PORTAL
  problem:
    code-portal-prefix: http://c.minlia.com/
  ### 系统忽略列表，此清单中的值将不进行鉴权
  ignored:
    urls:
      - /api/v1/permission/getMenuList/**
      - /api/v1/user/regist
      - /api/v1/common/**
#      - /swagger-ui.html
#      - /swagger-resources/**
#      - /swagger/**
      - /api/v1/open/**
#      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico





logging:
  level:
    ROOT: info
    com.minlia: debug
    jdbc.audit: error
    jdbc.sqltiming: error
    jdbc.resultset: error
    jdbc.connection: error
    jdbc.sqlonly: info
    jdbc.resultsettable: info
    org.springframework.boot.autoconfigure: info
    org.springframework.boot.web.servlet.context: debug
    org.springframework.web.cors: debug
    io.swagger.models.parameters: error
#    org.springframework.core.io.support: debug
